config/routes.rb
Rails.application.routes.draw do


# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'owners#home'

get '/login' => 'sessions#new'

post '/login' => 'sessions#create'
post '/owners/new' => 'owners#create'


get '/auth/:provider/callback', to: 'sessions#create'

get '/logout' => 'sessions#destroy'



resources :owners, only: [:new]

resources :owners, only: [:show] do
  resources :pets, only: [:show, :index,:new,:create,:edit,:update]
end

resources :clinics, only: [:index,:new,:create,:show]
resources :pets, only: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clinic.rb
class Clinic < ApplicationRecord
    has_many :pets
    has_many :owners, through: :pets

    validates :name, presence: true
    validates :addr, presence: true

    def self.available_clinic
      left_outer_joins(:pets).group('clinics.id').having('count(clinic_id) <5')
    end
    
end

app/models/owner.rb
class Owner < ApplicationRecord
    has_many :pets
    has_many :clinics, through: :pets

    validates :name, presence: true
    validates_format_of :name, :with => /\A([a-z\s])+\Z/i
    validates :email, uniqueness: true
    validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  #  validates :password, presence: true

    has_secure_password

end

app/models/pet.rb
class Pet < ApplicationRecord
    belongs_to :clinic
    belongs_to :owner

    validates :name, presence: true
    validates :breed, presence: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clinics_controller.rb
class ClinicsController < ApplicationController
  include ApplicationHelper
  include ClinicsHelper

  def index
    redirect_if_not_logged_in
    @clinics = Clinic.all
    @avaiables = Clinic.available_clinic
  end

  def new
    @clinic = Clinic.new
  end

  def create

    @clinic = Clinic.create(clinic_params)

    if !@clinic.save
      return render 'new'
    end

    redirect_to clinics_path
  end

  def show
    @clinic = Clinic.find_by(id: params[:id])

    if !@clinic
      #flash[:]
      redirect_to clinics_path
    end

  end

end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  include ApplicationHelper
  include OwnersHelper

  def home
    @owners = Owner.all
  end

  def new
    @owner = Owner.new
  end

  def show
    if session[:owner_id]==id_from_url.to_i
      @owner = Owner.find_by(id: id_from_url)
    else
      flash[:message] = "You are accessing other owner's page!!"
      redirect_to owner_path(current_owner)
    end

  end

  def create
    @owner = Owner.create(owner_params)


    if !@owner.save
    return render 'new'
    end

    session[:owner_id] = @owner.id

    redirect_to owner_path(@owner)
  end

  private

   def id_from_url
     params.permit(:id)[:id]
   end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  include ApplicationHelper

  def new
    @owner = Owner.find_by(id: params[:owner_id])
  end

  def create
    redirect_if_not_logged_in
    if Clinic.available_clinic.exists?(pet_params[:clinic_id])
      @pet = Pet.create(pet_params)
      redirect_to owner_pet_path(@pet.owner.id,@pet)
    else
      flash[:full]= "Current clinic is full with other pets. Choose other clinic for your pet"
      redirect_to new_owner_pet_path(current_owner)
    end


    # redirect_to vs render  -- Use render as much as possible
  end

  def destroy
    redirect_if_not_logged_in
          @pet = Pet.find_by(id: params[:id])
          if @pet == nil
            flash[:message]="The pet is not found in database"
          elsif current_owner.id == @pet.owner_id
            flash[:message]="#{@pet.name} is gone"
            @pet.delete
          else
            flash[:message]="You are not allowed to delete this pet"
          end
            redirect_to owner_path(current_owner)
  end

  def show
    redirect_if_not_logged_in
    @pet = Pet.find_by(id: params[:id])
    if !@pet
      redirect_to owner_path(current_owner)
    end
    
  end

  def edit
    redirect_if_not_logged_in
             if Pet.find(params[:id]) == nil
               flash[:message]="There is no information about this pet"
               redirect_to owner_path(current_owner)
             elsif current_owner.id == Pet.find(params[:id]).owner.id
               @pet = Pet.find(params[:id])
               render 'edit'
             else
               flash[:message]="You are not allowed to edit this pet's information"
               redirect_to owner_path(current_owner)
             end

  end

  def update
    redirect_if_not_logged_in
         @pet = Pet.find(params[:id])
         if current_owner.id != @pet.owner_id
             flash[:message] = "It is not your pet!!"
             redirect_to owner_path(current_owner)
         else
           updated = @pet.update(name: pet_params[:name],breed: pet_params[:breed],desc: pet_params[:desc],clinic_id: pet_params[:clinic_id])
           return redirect_to edit_owner_pet_path(@pet.owner.id, @pet) unless updated
           flash[:update] = "Your pet information was updated"
           redirect_to owner_pet_path(@pet.owner)
         end
  end

  def index
    redirect_if_not_logged_in
    @owner = Owner.find_by(id: current_owner[:id])
    @pets =  @owner.pets
  end

  private

  def pet_params
    params.require(:pet).permit(:id,:name,:breed,:desc,:owner_id,:clinic_id)
  end
end

app/controllers/sessions_controller.rb
require 'pry'
class SessionsController < ApplicationController
include ApplicationHelper

  def new
    if logged_in?
      flash[:message] = "You are already logged in. Please logout first, if you want to login as other owner"
      redirect_to(current_owner)
    end
  end

  def create

    if auth!=nil
        @owner = Owner.find_or_create_by(uid: auth['uid']) do |u|
            u.name = auth['info']['name']
            u.email = auth['info']['email']
            u.image = auth['info']['image']
            u.password = SecureRandom.hex(9)
          end
        @owner.save
        session[:owner_id] = @owner.id
        flash[:message] = "Login successful with your facebook account"
    else
      owner = Owner.find_by(name: owner_params[:name])

      if !owner
        flash[:message] = "Name is not found in the db, try with other name"
        return render 'new'
      end

      owner = owner.try(:authenticate, owner_params[:password])

      if !owner
        flash[:message] = "Wrong password, try with right password"
        return render 'new'
      end

      session[:owner_id] = owner.id
      @owner = owner
      flash[:message] = "successfully login!"

    end


    redirect_to owner_path(@owner)

  end

  def destroy
    session.clear
    redirect_to root_path
  end

  private

  def auth
    request.env['omniauth.auth']
  end

  def owner_params
    params.require(:owner).permit(
      :email, :password, :name, :password_confirmation
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def logged_in?
       !!current_owner
  end

   def current_owner
     @current_owner ||= Owner.find_by(id: session[:owner_id]) if session[:owner_id]
   end


   def redirect_if_not_logged_in
     if !logged_in?
       flash[:message] = "Login is required"
       redirect_to "/login"
     end
   end
end

app/helpers/clinics_helper.rb
module ClinicsHelper

  def clinic_params
    params.require(:clinic).permit(:name, :addr)
  end

end

app/helpers/owners_helper.rb
module OwnersHelper

  def owner_params
    params.require(:owner).permit(:name, :email, :password, :password_confirmation)
  end


end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/clinics/index.html.erb
<div class="topnav">
  <a href="/">Home</a>
  <a href=<%=owner_path(current_owner)%>>Owner</a>
  <a class="active" href="/clinics">Clinic list</a>
</div>


<h1>Clinic list</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Availability</th>
    <th>Owner list</th>
    </tr>
  <%@clinics.each do |clinic|%>
  <tr>
    <td><%=clinic.name%></td>
    <td><%=clinic.addr%></td>
    <td><%=@avaiables.exists?(clinic.id) ? "Yes" : "No"%></td>
    <td>
    <%clinic.owners.distinct.each do |owner|%>
      <%=owner.name%>
    <%end%>
    </td>
  </tr>
  <%end%>
  <tr>
    <td><a href=<%=new_clinic_path%>><button>Add another clinic</button></a></td>
  </tr>
</table>

app/views/clinics/new.html.erb
<div class="topnav">
  <a href="/">Home</a>
  <a href=<%=owner_path(current_owner)%>>Current_owner</a>
  <a class="active" href=<%=new_clinic_path%>>Add a new Clinic</a>
</div>

<%@clinic.errors.full_messages.each do |err|%>
  <li><%=err%></li>
  <%end%>

<h1>Clinic Add form</h1>
<%= form_for @clinic do |f| %>
  name: <%= f.text_field :name %>
  Address: <%= f.text_field :addr %>
  <%= f.submit "Submit" %>
<% end %>

app/views/clinics/show.html.erb
<div class="topnav">
  <a href="/">Home</a>
  <a href=<%=owner_path(current_owner)%>>Current_owner</a>
  <a class="active">Current Clinic</a>
</div>

<h1><%=@clinic.name%> page!</h1>

<p>Clinic's address is <%=@clinic.addr%></p><br>

<%@clinic.pets.each do |pet|%>
<li><%=pet.name%> in <%=@clinic.name%></li>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pet-Management-System</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/owners/home.html.erb
<div class="topnav">
  <a class="active" href="/">Home</a>
  <a href="/login">Login</a>
  <a href="/clinics">Clinic list</a>
</div>

<h1>Welcome to pet management system</h1>

<h2>Owner list</h2>

<table>
  <tr>
    <th>Owner name</th>
    <th>Owner email</th>
    </tr>
  <%@owners.each do |owner|%>
  <tr><td>Name: <%=owner.name%></td>
    <td>Email: <%=owner.email%></td>
  </tr>
  <%end%>
</table>

app/views/owners/new.html.erb
<div class="topnav">
  <a href="/">Home</a>
  <a href="/login">Login</a>
  <a class="active" href="/owners/new">Sign Up</a>
</div>

<%@owner.errors.full_messages.each do |err|%>
  <li><%=err%></li>
  <%end%>

<h1>Owner Sign Up form</h1>
<%= form_for :owner do |f| %>
  Username: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>
<% end %>

app/views/owners/show.html.erb
<div class="topnav">
  <a href="/">Home</a>
  <a class="active" href="/login">Login</a>
  <a href=<%=owner_pets_path(@owner)%>>Pet list</a>
  <a href="/clinics">Clinic list</a>
</div>

<%= render partial: "pets/flash", locals: {key: 'message'} %>

<h1>Welcome, <%=@owner.name%></h1>
  <h2>Email: <%= @owner.email %></h2>
<table class="ownershow">
  <tr>
    <th>
      <%= link_to('Adopt pet', new_owner_pet_path(@owner)) %>
    </th>
    <th>
      <%= link_to('Logout', logout_path) %>
    </th>
  </tr>
</table>

app/views/pets/_flash.html.erb
<% if flash[key] %>
  <%= flash[key] %>
<% end %>

app/views/pets/edit.html.erb
<div class="topnav">
  <a href=<%=owner_path(@pet.owner)%>>Owner page</a>
  <a class="active" href=<%=edit_owner_pet_path(@pet.owner.id,@pet)%>>Edit</a>
</div>

<%= render partial: "flash", locals: {key: 'update'} %>

<h1>Pet Edit form</h1>

<%= form_for :pet, url: owner_pet_path(@pet.owner, @pet),method: :patch do |f| %>
  <%=f.hidden_field :owner_id, :value =>@pet.owner.id%>
  Pet Name: <%= f.text_field :name %>
  Pet Breed: <%= f.text_field :breed %>
  Pet Description: <%= f.text_field :desc %>

  Pet Clinic: <%= f.collection_select :clinic_id, Clinic.all, :id, :name%>

  <%= f.submit "Edit" %>
<% end %>

app/views/pets/index.html.erb
<div class="topnav">
  <a href="/">Home</a>
  <a href="/login">Login</a>
  <a class="active" href=<%=owner_pets_path(@owner)%>>Pet list</a>
  <a href="/clinics">Clinic list</a>
</div>

<%= render partial: "flash", locals: {key: 'update'} %>

<h1> Pet list</h1>
<table class="petlist">
<tr>
  <th>Name</th>
  <th>Breed</th>
  <th>Clinic</th>
  <th>Edit pet info</th>
  <th>Bye to your pet</th>
</tr>
<%@pets.each do |pet|%>
<tr>
  <td><a class="petshow" href=<%=owner_pet_path(pet.owner.id,pet.id)%>><%=pet.name%></a></td>
  <td><%=pet.breed%></td>
  <td><%=pet.clinic.name%></td>
  <td><%=link_to("Edit",edit_owner_pet_path(pet.owner.id,pet.id))%></td>
  <td><%=link_to("Bye Bye",pet_path(pet),:method => 'delete')%></td>
</tr>
<%end%>
</table>

app/views/pets/new.html.erb
<div class="topnav">
  <a href=<%=owner_path(@owner)%>>Owner page</a>
  <a class="active" href=<%=new_owner_pet_path(@owner)%>>Adoption</a>
</div>

<%= render partial: "flash", locals: {key: 'full'} %>

<h1>Pet adoption form</h1>

<%= form_for :pet, url: owner_pets_path(@owner) do |f| %>
  <%=f.hidden_field :owner_id, :value =>@owner.id%>
  Pet Name: <%= f.text_field :name %>
  Pet Breed: <%= f.text_field :breed %>
  Pet Description: <%= f.text_field :desc %>

  Pet Clinic: <%= f.collection_select :clinic_id, Clinic.all, :id, :name%>

  <%= f.submit "Adopt" %>
<% end %>

app/views/pets/show.html.erb
<div class="topnav">
  <a href="/">Home</a>
  <a href=<%=owner_path(@pet.owner)%>>Owner</a>
  <a class="active" href=<%=owner_pet_path(@pet.owner.id,@pet)%>>Current Pet</a>
  <a href="/clinics">Clinic list</a>
</div>

<%= render partial: "flash", locals: {key: 'update'} %>

<h1><%=@pet.name%>'s page</h1>
<p>Owner name: <%=@pet.owner.name%></p>
<p>Breed: <%=@pet.breed%></p>
<p>Description: <%=@pet.desc%></p>
<p>Clinic name: <%=@pet.clinic.name%></p>